server:
  port: 8080
spring:
  application.name: bdb-approvals-back
  jackson:
    default-property-inclusion: non_null
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc.time_zone: UTC
  datasource:
    url: jdbc:h2:mem:bdbapprovals;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
    username: sa
    password: sa
  flyway:
    enabled: true
    locations: classpath:db/migration
management:
  endpoints.web.exposure.include: health,info,metrics
  endpoint.health.probes.enabled: true

app:
  security:
    audience: ${AZ_API_AUDIENCE:api://mock}
  notifications:
    channel: email
  email:
    from: ${SES_FROM:no-reply@example.com}


