spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/${AZ_TENANT_ID}/v2.0
          jwk-set-uri: https://login.microsoftonline.com/${AZ_TENANT_ID}/discovery/v2.0/keys
app:
  security:
    mock-enabled: false