server:
  port: 8080

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  datasource:
    url: ${JDBC_URL}
    username: ${JDBC_USER}
    password: ${JDBC_PASS}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH_ISSUER}
          audiences: ${OAUTH_AUDIENCE}

app:
  security:
    audience: ${OAUTH_AUDIENCE}
    mock-enabled: ${APP_SECURITY_MOCK_ENABLED:false}

  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200}
    allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,OPTIONS}
    allowed-headers: ${CORS_ALLOWED_HEADERS:Authorization,Content-Type}

ses:
  region: ${AWS_REGION}
  from: ${SES_FROM}
  smtp:
    host: ${SES_SMTP_HOST}
    username: ${SES_SMTP_USERNAME}
    password: ${SES_SMTP_PASSWORD}